name: CI
on: [push]
jobs:
  cabal-ci:
    name: Cabal CI: GHC ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['8.2.2', '8.4.4', '8.6.5', '8.8.3', '8.10.1']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Haskell
        uses: actions/setup-haskell@v1.1.3
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: latest
      - name: Update Cabal
        run: cabal update
      - name: Build
        run: cabal new-build --enable-tests --enable-benchmarks
      - name: Test
        run: cabal new-test --enable-tests
